# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy Staging
concurrency: deploy-${{ github.repository }}-${{ github.workflow }}

on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ main ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: staging
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: build-artifact
      - uses: actions/setup-node@v2
        with:
          node-version: 16
        #install serverless
      - name: Install Serverless Framework
        run: npm install -g serverless
        # authentication
        #serverless deploy
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::344268766757:role/personal-dev-cd-nonprod
          aws-region: us-east-1
          role-session-name: "${{ github.actor }}"
      # deploy serverless
      - name: Deploy serverless
        run: |
          serverless deploy --stage staging
