# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f aws_requirements.txt ]; then pip install -t src/vendor -r aws_requirements.txt ; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude "src/vendor/*"
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --statistics --exclude "src/vendor/*"
  deploy:
    name: Deploy serverless lambda
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
        #install serverless
      - name: Install Serverless Framework
        run: npm install -g serverless
        # authentication
        #serverless deploy
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::344268766757:role/personal-dev-cd-nonprod
          role-session-name: personal-dev-cd-role
          aws-region: us-east-1
      # deploy serverless
      - name: Deploy serverless
        run: |
          serverless deploy --stage staging